# Generated by Django 5.1.6 on 2026-01-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('path', 'ip_address', 'date')},
            },
        ),
    ]
