# Generated by Django 5.1.6 on 2026-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
