# Generated by Django 5.1.6 on 2026-01-20 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0003_costtype_cost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
