# Generated by Django 5.1.6 on 2025-02-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='index',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
