# Generated by Django 5.1.6 on 2025-03-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_quotes_youtube_created_at_youtube_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='attribute',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
