# Generated by Django 5.1.6 on 2025-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='work',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
