# Generated by Django 5.1.6 on 2025-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Új', 'Új'), ('Megtekintve', 'Megtenkintve'), ('Válaszolva', 'Válaszolva')], default='Új', max_length=50, null=True),
        ),
    ]
