# Generated by Django 5.1.6 on 2025-05-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_contact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, null=True)),
            ],
        ),
    ]
