# Generated by Django 5.1.6 on 2025-12-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_categorynew_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(null=True, upload_to='mews/'),
        ),
    ]
