# Generated by Django 5.1.6 on 2026-01-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=10000, null=True),
        ),
    ]
