# Generated by Django 5.1.6 on 2026-01-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=13000, null=True),
        ),
    ]
