# Generated by Django 5.1.6 on 2025-03-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_billingaddress_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Új', 'Új'), ('Megtekintve', 'Megtenkintve'), ('Összekészítve', 'Összekészítve'), ('Becsomagolva', 'Becsomagolva'), ('Feladva', 'Feladva'), ('Kiszállítva', 'Kiszállítva')], default='Új', max_length=50, null=True),
        ),
    ]
