# Generated by Django 5.1.6 on 2025-03-11 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_all_cost_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='brutto_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='net_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shippingcost'),
        ),
    ]
