# Generated by Django 5.1.6 on 2025-03-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Új', 'Új'), ('Megtekintve', 'Megtekintve'), ('Összekészítve', 'Összekészítve'), ('Becsomagolva', 'Becsomagolva'), ('Feladva', 'Feladva'), ('Kiszállítva', 'Kiszállítva')], default='Új', max_length=50, null=True),
        ),
    ]
