# Generated by Django 5.1.6 on 2025-03-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
