# Generated by Django 5.1.6 on 2025-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shippingaddress_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='personal',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
